### ISSUE TITLE
IndexError when checking `pelican-youtube-thumbnails`

### ISSUE THREAD

**Issue by layday** [henryiii/check-sdist#5]
```
$ pipx run check-sdist
* Creating venv isolated environment...
* Installing packages in isolated environment... (setuptools >= 40.8.0, wheel)
* Getting build dependencies for sdist...
running egg_info
writing pelican_youtube_thumbnails.egg-info/PKG-INFO
writing dependency_links to pelican_youtube_thumbnails.egg-info/dependency_links.txt
writing requirements to pelican_youtube_thumbnails.egg-info/requires.txt
writing top-level names to pelican_youtube_thumbnails.egg-info/top_level.txt
reading manifest file 'pelican_youtube_thumbnails.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'COPYING'
writing manifest file 'pelican_youtube_thumbnails.egg-info/SOURCES.txt'
* Building sdist...
running sdist
running egg_info
writing pelican_youtube_thumbnails.egg-info/PKG-INFO
writing dependency_links to pelican_youtube_thumbnails.egg-info/dependency_links.txt
writing requirements to pelican_youtube_thumbnails.egg-info/requires.txt
writing top-level names to pelican_youtube_thumbnails.egg-info/top_level.txt
reading manifest file 'pelican_youtube_thumbnails.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'COPYING'
writing manifest file 'pelican_youtube_thumbnails.egg-info/SOURCES.txt'
running check
creating pelican-youtube-thumbnails-0.3.2
creating pelican-youtube-thumbnails-0.3.2/pelican
creating pelican-youtube-thumbnails-0.3.2/pelican/plugins
creating pelican-youtube-thumbnails-0.3.2/pelican/plugins/youtube_thumbnails
creating pelican-youtube-thumbnails-0.3.2/pelican_youtube_thumbnails.egg-info
creating pelican-youtube-thumbnails-0.3.2/tests
copying files to pelican-youtube-thumbnails-0.3.2...
copying COPYING -> pelican-youtube-thumbnails-0.3.2
copying MANIFEST.in -> pelican-youtube-thumbnails-0.3.2
copying README.md -> pelican-youtube-thumbnails-0.3.2
copying setup.py -> pelican-youtube-thumbnails-0.3.2
copying pelican/__init__.py -> pelican-youtube-thumbnails-0.3.2/pelican
copying pelican/plugins/youtube_thumbnails/__init__.py -> pelican-youtube-thumbnails-0.3.2/pelican/plugins/youtube_thumbnails
copying pelican/plugins/youtube_thumbnails/logo.png -> pelican-youtube-thumbnails-0.3.2/pelican/plugins/youtube_thumbnails
copying pelican/plugins/youtube_thumbnails/youtube_thumbnails.py -> pelican-youtube-thumbnails-0.3.2/pelican/plugins/youtube_thumbnails
copying pelican_youtube_thumbnails.egg-info/PKG-INFO -> pelican-youtube-thumbnails-0.3.2/pelican_youtube_thumbnails.egg-info
copying pelican_youtube_thumbnails.egg-info/SOURCES.txt -> pelican-youtube-thumbnails-0.3.2/pelican_youtube_thumbnails.egg-info
copying pelican_youtube_thumbnails.egg-info/dependency_links.txt -> pelican-youtube-thumbnails-0.3.2/pelican_youtube_thumbnails.egg-info
copying pelican_youtube_thumbnails.egg-info/requires.txt -> pelican-youtube-thumbnails-0.3.2/pelican_youtube_thumbnails.egg-info
copying pelican_youtube_thumbnails.egg-info/top_level.txt -> pelican-youtube-thumbnails-0.3.2/pelican_youtube_thumbnails.egg-info
copying tests/test_youtube_thumbnails.py -> pelican-youtube-thumbnails-0.3.2/tests
Writing pelican-youtube-thumbnails-0.3.2/setup.cfg
Creating tar archive
removing 'pelican-youtube-thumbnails-0.3.2' (and everything under it)
Successfully built pelican-youtube-thumbnails-0.3.2.tar.gz
Traceback (most recent call last):
  File "/Users/dimitris/.local/pipx/.cache/0e981b5e61d209f/bin/check-sdist", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/dimitris/.local/pipx/.cache/0e981b5e61d209f/lib/python3.11/site-packages/check_sdist/__main__.py", line 102, in main
    raise SystemExit(compare(args.source_dir, not args.no_isolation, args.verbose))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dimitris/.local/pipx/.cache/0e981b5e61d209f/lib/python3.11/site-packages/check_sdist/__main__.py", line 28, in compare
    sdist = sdist_files(source_dir, isolated) - {"PKG-INFO"}
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dimitris/.local/pipx/.cache/0e981b5e61d209f/lib/python3.11/site-packages/check_sdist/sdist.py", line 26, in sdist_files
    return frozenset(n.split("/", maxsplit=1)[1] for n in tar.getnames())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dimitris/.local/pipx/.cache/0e981b5e61d209f/lib/python3.11/site-packages/check_sdist/sdist.py", line 26, in <genexpr>
    return frozenset(n.split("/", maxsplit=1)[1] for n in tar.getnames())
                     ~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by henryiii** [comment]
With #6, I now get:

```
SDist does not match git

SDist only:


Git only:
  .flake8
  .gitignore
  CHANGELOG.md
  pelican/__init__.py
  pelican/plugins/__init__.py
  tests/test_data/image_240p.png
  tests/test_data/image_240p_with_overlay.png
```
